steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=Client
      - --key=env
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/fullstack-client:latest
      - --cache-from
      - gcr.io/$PROJECT_ID/fullstack-client:latest
      - .
    env:
      - APP_LISTEN_PORT=80
    secretEnv:
      - REACT_APP_API_URI

images:
  - gcr.io/$PROJECT_ID/fullstack-client
