steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - 'docker build
        --tag "gcr.io/$PROJECT_ID/fullstack-client:latest"
        --cache-from "gcr.io/$PROJECT_ID/fullstack-client:latest"
        --build-arg "REACT_APP_API_URI=$$REACT_APP_API_URI"
        --build-arg "APP_LISTEN_PORT="
        .'
    secretEnv:
      - REACT_APP_API_URI

images:
  - gcr.io/$PROJECT_ID/fullstack-client

secrets:
  - kmsKeyName: projects/apollo-server-227201/locations/global/keyRings/Client/cryptoKeys/env
    secretEnv:
      REACT_APP_API_URI: CiQAQCQ1fnOel9ZH/lcjxLNCAng5xmhHqMxPjkYdwfDKa/O2Dp4SRABm4wnPL6x3nJ9aQ1QPauutDvWz3pJmamE/hhHO9umte24UQ70r5Clf/iJ5N5AvKVMQeZ643O7exm+h2RWaVmuLeOZL
