steps:
  # Build container
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - 'docker build
        --tag "gcr.io/$PROJECT_ID/$REPO_NAME"
        --tag "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
        --cache-from "gcr.io/$PROJECT_ID/$REPO_NAME"
        --build-arg "REACT_APP_API_URI=$$REACT_APP_API_URI"
        .'
    secretEnv:
      - REACT_APP_API_URI

  # Deploy container and rolling update
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - set
      - image
      - deployment/frontend
      - fullstack-client-sha256=gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
    env:
      - CLOUDSDK_COMPUTE_ZONE=us-central1-a
      - CLOUDSDK_CONTAINER_CLUSTER=frontend

# State the images that should be generated for metadata purposes
images:
  - gcr.io/$PROJECT_ID/$REPO_NAME

# Encrypted variables to pass in at build time, runtime variables/secrets are in deployment configuration
secrets:
  - kmsKeyName: projects/apollo-server-227201/locations/global/keyRings/Client/cryptoKeys/env
    secretEnv:
      REACT_APP_API_URI: CiQAQCQ1fv/NxBtIeYkfF7jI2LQaaCRVq84KJ3MHkt+exzHotk4SRABm4wnPrXqO5KErNzTpVMFqt2ziBev706wx9BF/CsZtCHiR/Y3Tgqkc687iGRkQjfqg9E4fflXWvWGkpYd2axBS4L68
