steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=Client
      - --key=env
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --build-arg
      - $$REACT_APP_API_URI
      - -t
      - gcr.io/$PROJECT_ID/fullstack-client:latest
      - --cache-from
      - gcr.io/$PROJECT_ID/fullstack-client:latest
      - .

images:
  - gcr.io/$PROJECT_ID/fullstack-client
