steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --build-arg
      - REACT_APP_API_URI=$$REACT_APP_API_URI
      - -t
      - gcr.io/$PROJECT_ID/fullstack-client:latest
      - --cache-from
      - gcr.io/$PROJECT_ID/fullstack-client:latest
      - .
    secretEnv:
      - REACT_APP_API_URI

images:
  - gcr.io/$PROJECT_ID/fullstack-client

secrets:
  - kmsKeyName: projects/apollo-server-227201/locations/global/keyRings/Client/cryptoKeys/env
    secretEnv:
      REACT_APP_API_URI: CiQAQCQ1fu26d+m3LEheW2oHvi384/5a/sSMqBCUVipOJPLmnj8SSABm4wnPZyfgTeWqbCQ5xmJ2O6Q2l2rtpf2/AFmAjclF4uvNjyrOfJnQC4FSXuc0P68vPHgiaadtOr36LOSmALag4AiU0lDq2g==
